ceph rbd support

diff --git a/runner b/runner
--- a/runner
+++ b/runner
@@ -40,7 +40,7 @@ if [ -e "$confdir"/defaults ]; then
 elif [ -e "$libdir"/defaults ]; then
     . "$libdir/defaults"
 else
-    echo "WARNING: defaults file not found (in either \"$confdir\" or \"$libdir\"), so skipping loading it"
+    echo "WARNING: defaults file not found (in either \"$confdir\" or \"$libdir\"), so skipping loading it" >&2
 fi
 
 net_bridge_default="$net_bridge"
@@ -207,7 +207,7 @@ add_virtio_bus() {
 
 IFS=$'\n'
 for diskname in $(set | awk -F= '$1 ~ /^disk[0-9]+_file$/ {print $0}' | grep -Eo "^disk[0-9]+" | sort -u); do
-    disk_file=$(set | awk -F= -v name="$diskname" '$1 == name "_file" {print $2}')
+    disk_file=$(set | awk -F= -v name="$diskname" '$1 == name "_file"' | cut -d'=' -f2-)
     disk_format=$(set | awk -F= -v name="$diskname" '$1 == name "_format" {print $2}')
     disk_type=$(set | awk -F= -v name="$diskname" '$1 == name "_type" {print $2}')
 
@@ -217,9 +217,16 @@ for diskname in $(set | awk -F= '$1 ~ /^disk[0-9]+_file$/ {print $0}' | grep -Eo
         if [ ! -e "$disk_file" -a -e "$imgPath"/"$disk_file" ]; then
             disk1_file="$imgPath"/"$disk_file"
         fi
-        if [ ! -e "$disk_file" ]; then
-            echo "ERROR: disk1_file \"$disk_file\" not found"
-            exit 2;
+        if qemu-img info -f rbd "$disk_file" >/dev/null 2>&1; then
+#            echo "DEBUG: found good rbd disk"
+            true
+        elif [ ! -e "$disk_file" ]; then
+            if [ "$dry_run" = 1 ]; then
+                echo "WARNING: disk1_file \"$disk_file\" not found" >&2
+            else
+                echo "ERROR: disk1_file \"$disk_file\" not found" >&2
+                exit 2;
+            fi
         fi
     fi
     if [ -z "$disk_format" ]; then
@@ -284,8 +291,12 @@ for cdname in $(set | awk -F= '$1 ~ /^cd[0-9]+_file$/ {print $0}' | grep -Eo "^c
             cd1_file="$cdPath"/"$cd_file"
         fi
         if [ ! -e "$cd_file" ]; then
-            echo "ERROR: cd_file \"$cd_file\" not found"
-            exit 2
+            if [ "$dry_run" = 1 ]; then
+                echo "WARNING: cd_file \"$cd_file\" not found" >&2
+            else
+                echo "ERROR: cd_file \"$cd_file\" not found" >&2
+                exit 2
+            fi
         fi
     fi
     if [ -z "$cd_type" ]; then
