cleanup and beginning to merge runner with runner-vfio which isn't in the repo yet

diff --git a/runner b/runner
--- a/runner
+++ b/runner
@@ -52,10 +52,9 @@ net_type_default="virtio"
 
 cmd=()
 add() {
-    echo "$@ \\"
+    echo "    $@ \\"
     cmd+=("$@")
 }
-echo "qemu-system-x86_64 \\"
 
 #+==========================================================================
 # vm settings
@@ -68,11 +67,10 @@ else
     exit 1
 fi
 
-# TODO: validate that at least one net is there
-#if [ -z "$net1" ]; then
-#    echo "ERROR: net1 is required"
-#    exit 1
-#fi
+
+if [ -z "$vmnickname" ]; then
+    vmnickname="$vmname"
+fi
 
 #+==========================================================================
 # Command Line Arguments
@@ -117,22 +115,38 @@ fi
 
 #+==========================================================================
 
-add -enable-kvm 
+echo "qemu-system-x86_64 \\"
+add -enable-kvm
 add -m "$ram" -M q35
+if [ -n "$cpu" ]; then
+    # eg. for nested virtualization on a first generation i7
+    # cpu="Nehalem,+vmx"
+    add -cpu "$cpu"
+fi
 
-# this makes CentOS kernel panic
-#-cpu host
+if [ -n "$biosbin" ]; then
+    add -bios "$biosbin"
+fi
 
-# add this for nested virtualization
-#add -cpu Nehalem,+vmx
+# for backwards compat, "cpus" is assumed to mean cores with sockes=1
+if [ -z "$cores" -a -n "$cpus" ]; then
+    cores="$cpus"
+    sockets=1
+fi
+if [ -z "$sockets" ]; then
+    sockets=1
+fi
 
-add -smp "$cpus",sockets=1,cores="$cpus",threads=1
+add -smp "$cores",sockets="$sockets",cores="$cores",threads=1
 add -device ioh3420,bus=pcie.0,addr=1c.0,multifunction=on,port=1,chassis=1,id=root.1
 add -boot menu=on
 
 #=============================
 # disks TODO: change it to be more like the network stuff
 #=============================
+
+nextIndex=0
+disknum=0
 
 if [ -n "$disk1_file" ]; then
     if [ ! -e "$disk1_file" -a -e /var/lib/libvirt/images/"$disk1_file" ]; then
@@ -148,17 +162,6 @@ if [ -z "$disk1_format" ]; then
     disk1_format=qcow2
 fi
 
-if [ -n "$cdFile" ]; then
-    if [ ! -e "$cdFile" -a -e /var/lib/libvirt/images/"$cdFile" ]; then
-        cdFile=/var/lib/libvirt/images/"$cdFile"
-    fi
-    if [ ! -e "$cdFile" ]; then
-        echo "ERROR: cdFile \"$cdFile\" not found"
-        exit 2
-    fi
-fi
-
-#add -drive file=/dev/cdrom,media=cdrom,if=ide
 
 virtio_bus_added=0
 
@@ -170,9 +173,6 @@ add_virtio_bus() {
     fi
 }
 
-nextIndex=0
-
-disknum=0
 for diskname in $(set | awk -F= '$1 ~ /^disk[0-9]+_file$/ {print $0}' | grep -Eo "^disk[0-9]+" | sort -u); do
     disk_file=$(set | awk -F= -v name="$diskname" '$1 == name "_file" {print $2}')
     disk_format=$(set | awk -F= -v name="$diskname" '$1 == name "_format" {print $2}')
@@ -207,40 +207,48 @@ for diskname in $(set | awk -F= '$1 ~ /^disk[0-9]+_file$/ {print $0}' | grep -Eo
     let disknum++
 done
 
-if [ "$apparmor" = 1 ]; then
-    if [ -n "$cdFile" ]; then
-        # add the required files to this VM's profile
-        apparmor "$cdFile"
+#=============================
+# cd files TODO: change it to be more like the network stuff
+#=============================
+
+if [ -n "$cdFile" ]; then
+    if [ ! -e "$cdFile" -a -e "$cdPath"/"$cdFile" ]; then
+        cdFile="$cdPath"/"$cdFile"
+    fi
+    if [ ! -e "$cdFile" ]; then
+        echo "ERROR: cdFile \"$cdFile\" not found"
+        exit 2
     fi
 fi
 
-if [ "$cdType" = "ide" ]; then
-    index=$nextIndex
-    let nextIndex++
-    add -drive file=${cdFile},id=isocd,media=cdrom,index="$index" #-device ide-cd,bus=ide.1,drive=isocd
-elif [ "$cdType" = "virtio" ]; then
-    index=$nextIndex
-    let nextIndex++
-    if [ "$disk_type" = "virtio" ]; then
-        add_virtio_bus
+if [ -n "$cdFile" ]; then
+    if [ "$cdType" = "ide" ]; then
+        index=$nextIndex
+        let nextIndex++
+        add -drive file=${cdFile},id=isocd,media=cdrom,index="$index"
+    elif [ "$cdType" = "virtio" ]; then
+        index=$nextIndex
+        let nextIndex++
+        if [ "$disk_type" = "virtio" ]; then
+            add_virtio_bus
+        fi
+        if [ -n "$cdFile" ]; then
+            add -drive file=${cdFile},id=isocd,media=cdrom,index="$index"
+        fi
+    elif [ -z "$cdType" -a -z "$cdFile" ]; then
+        # no cd
+        echo -n
+    else
+        echo "ERROR: unsupported cdType \"$cdType\""
+        exit 2
     fi
-    if [ -n "$cdFile" ]; then
-        add -drive file=${cdFile},id=isocd,media=cdrom,index="$index" #-device ide-cd,bus=ahci.1,drive=isocd
-    fi
-elif [ -z "$cdType" -a -z "$cdFile" ]; then
-    # no cd
-    echo -n
-else
-    echo "ERROR: unsupported cdType \"$cdType\""
-    exit 2
 fi
 
 #=============================
 # network
 #=============================
 
-
-# Parse net* (net#_bridge=xxx and net#_mac=xxx)
+# Parse net* (net#_bridge=xxx, net#_mac=xxx, net#_type=xxx)
 # this number is used only for the qemu ids, not parsing config
 netnum=0
 for netname in $(set | awk -F= '$1 ~ /^net[0-9]+_(bridge|mac)$/ {print $0}' | grep -Eo "^net[0-9]+" | sort -u); do
@@ -302,8 +310,8 @@ for netname in $(set | awk -F= '$1 ~ /^net[0-9]+_(bridge|mac)$/ {print $0}' | gr
     fi
 
     #shorten the ifname (max 15 characters)
-    ifname="$vmname-$netname"
-    shortenedName="$vmname"
+    ifname="$vmnickname-$netname"
+    shortenedName="$vmnickname"
     while [ "${#ifname}" -ge 15 ]; do
         shortenedName=${shortenedName:0:-1}
         ifname="$shortenedName-$netname"
@@ -314,16 +322,11 @@ for netname in $(set | awk -F= '$1 ~ /^net[0-9]+_(bridge|mac)$/ {print $0}' | gr
     # or just make sure names are short and be limited in how many nics to have (short name = filename, long name = ?)
 
     addr=$((12+netnum))
-    add -netdev type=tap,id=net"$netnum",ifname="$ifname",script=${bridgeScript},downscript=no,vhost=on 
-    add -device "$netDevice",mac="$net_mac",netdev=net"$netnum",bus=pcie.0,addr=0x"$addr",id=net"$netnum"
+    add -netdev type=tap,id=net"$netnum",ifname="$ifname",script=${bridgeScript},downscript=no
+    add -device "$netDevice",mac="$net_mac",netdev=net"$netnum"
     let netnum++
 done
 
-#=============================
-# other
-#=============================
-
-# -rtc-td-hack 
 
 #=============================
 # monitor
@@ -353,24 +356,46 @@ elif [ -n "$vgaType" ]; then
     # std,qxl,cirrus,etc.
     add -vga "$vgaType"
 else
-    # otherwise the qemu default is cirrus, but let's change it to vmware
-    add -vga "vmware"
+    if [ -z "$DISPLAY" ]; then
+        echo "No X display... enabling VNC"
+        add -vnc :"$vncport"
+    else
+        # otherwise the qemu default is cirrus, but let's change it to vmware
+        add -vga "vmware"
+    fi
 fi
+
+#=============================
+# apparmor
+#=============================
 
 if [ "$apparmor" = 1 ]; then
     apparmor "$disk1"
     apparmor "$disk2"
     apparmor "$isovirtiowin"
+
+    if [ -n "$cdFile" ]; then
+        apparmor "$cdFile"
+    fi
+    if [ -n "$biosbin" ]; then
+        apparmor "$biosbin"
+    fi
+
 # TODO: automatically generate the bridge profile too? it's not just a single line... it has its own executables it uses too
 #	apparmor "$bridgeScript" rix
 
     # apply the policy (to all VMs)
-    aa-enforce /etc/apparmor.d/usr.bin.qemu-system-x86_64
+    if [ "$dry_run" != 1 ]; then
+        aa-enforce /etc/apparmor.d/usr.bin.qemu-system-x86_64
+    fi
 fi
 
 #=============================
 
 if [ "$dry_run" != 1 ]; then
     qemu-system-x86_64 "${cmd[@]}"
+    status=$?
 fi
+
+exit $status
 
