load vm settings after CLI handling

diff --git a/runner b/runner
--- a/runner
+++ b/runner
@@ -69,6 +69,25 @@ append() {
     cmd_append+=("$@")
 }
 
+
+#+==========================================================================
+# Command Line Arguments
+#+==========================================================================
+
+dry_run=0
+verbose=0
+while [ "$#" != 0 ]; do
+    if [ "$1" = "-n" ]; then
+        dry_run=1
+    elif [ "$1" = "-v" ]; then
+        verbose=1
+    else
+        echo "ERROR: unsupported argument: \"$1\""
+        exit 1
+    fi
+    shift
+done
+
 #+==========================================================================
 # vm settings
 #+==========================================================================
@@ -84,25 +103,6 @@ fi
 if [ -z "$vmnickname" ]; then
     vmnickname="$vmname"
 fi
-
-#+==========================================================================
-# Command Line Arguments
-#+==========================================================================
-
-dry_run=0
-verbose=0
-while [ "$#" != 0 ]; do
-    if [ "$1" = "-n" ]; then
-        shift
-        dry_run=1
-    elif [ "$1" = "-v" ]; then
-        shift
-        verbose=1
-    else
-        echo "ERROR: unsupported argument: \"$1\""
-        exit 1
-    fi
-done
 
 #+==========================================================================
 # for apparmor
