improving the defaults settings
SYNTAX: changed "diskType=..." "cdType=..." defaults to be like the
others: "disk_type=..."
BUG: cd_type wasn't used properly

diff --git a/runner b/runner
--- a/runner
+++ b/runner
@@ -207,71 +207,71 @@ add_virtio_bus() {
 
 IFS=$'\n'
 for diskname in $(set | awk -F= '$1 ~ /^disk[0-9]+_file$/ {print $0}' | grep -Eo "^disk[0-9]+" | sort -u); do
-    disk_file=$(set | awk -F= -v name="$diskname" '$1 == name "_file"' | cut -d'=' -f2-)
-    disk_format=$(set | awk -F= -v name="$diskname" '$1 == name "_format" {print $2}')
-    disk_type=$(set | awk -F= -v name="$diskname" '$1 == name "_type" {print $2}')
+    diskN_file=$(set | awk -F= -v name="$diskname" '$1 == name "_file"' | cut -d'=' -f2-)
+    diskN_format=$(set | awk -F= -v name="$diskname" '$1 == name "_format" {print $2}')
+    diskN_type=$(set | awk -F= -v name="$diskname" '$1 == name "_type" {print $2}')
 
-#    echo "DEBUG: file = $disk_file, format = $disk_format, type = $disk_type"
+#    echo "DEBUG: file = $diskN_file, format = $diskN_format, type = $diskN_type"
 
-    if [ -n "$disk_file" ]; then
-        if [ ! -e "$disk_file" -a -e "$imgPath"/"$disk_file" ]; then
-            disk1_file="$imgPath"/"$disk_file"
+    if [ -n "$diskN_file" ]; then
+        if [ ! -e "$diskN_file" -a -e "$img_path"/"$diskN_file" ]; then
+            disk1_file="$img_path"/"$diskN_file"
         fi
-        if qemu-img info -f rbd "$disk_file" >/dev/null 2>&1; then
+        if qemu-img info -f rbd "$diskN_file" >/dev/null 2>&1; then
 #            echo "DEBUG: found good rbd disk"
             true
-        elif [ ! -e "$disk_file" ]; then
+        elif [ ! -e "$diskN_file" ]; then
             if [ "$dry_run" = 1 ]; then
-                echo "WARNING: disk1_file \"$disk_file\" not found" >&2
+                echo "WARNING: disk1_file \"$diskN_file\" not found" >&2
             else
-                echo "ERROR: disk1_file \"$disk_file\" not found" >&2
+                echo "ERROR: disk1_file \"$diskN_file\" not found" >&2
                 exit 2;
             fi
         fi
     fi
-    if [ -z "$disk_format" ]; then
-        if [ -n "$diskFormat" ]; then
+    if [ -z "$diskN_format" ]; then
+        if [ -n "$disk_format" ]; then
             # if set, we use the default
-            disk_format="$diskFormat"
+            diskN_format="$disk_format"
         else
             # if no default set, we just assume raw for special, qcow2 otherwise
             if file $(readlink -f /dev/data/win7a) | grep -q "block special"; then
-                disk_format=raw
+                diskN_format=raw
             else
-                disk_format=qcow2
+                diskN_format=qcow2
             fi
         fi
     fi
-    if [ -z "$disk_type" ]; then
-        if [ -n "$diskType" ]; then
-            disk_type="$diskType"
+    if [ -z "$diskN_type" ]; then
+        if [ -n "$disk_type" ]; then
+            diskN_type="$disk_type"
         else
-            disk_type=ide
+            diskN_type=ide
         fi
     fi
 
     if [ "$apparmor" = 1 ]; then
         # add the required files to this VM's profile
-        apparmor "$disk_file"
+        apparmor "$diskN_file"
     fi
 
-    if [ "$disk_type" = "virtio" ]; then
+    if [ "$diskN_type" = "virtio" ]; then
         add_virtio_bus
     fi
 
-    if [ "$disk_type" = "ide" ]; then
+    if [ "$diskN_type" = "ide" ]; then
         #IDE disks
         #  new ... works in manjaro, intended to work with multiple disks
-        add -drive file=${disk_file},id=${diskname},format=${disk_format},index=${nextIndex},media=disk,discard=on
+        add -drive file=${diskN_file},id=${diskname},format=${diskN_format},index=${nextIndex},media=disk,discard=on
         let nextIndex++
-    elif [ "$disk_type" = "virtio" ]; then
+    elif [ "$diskN_type" = "virtio" ]; then
         #virtio disks
-        if [ -n "$disk_file" ]; then
-            add -drive file=${disk_file},id=${diskname},format=${disk_format},index=${nextIndex},media=disk,if=virtio,discard=on
+        if [ -n "$diskN_file" ]; then
+            add -drive file=${diskN_file},id=${diskname},format=${diskN_format},index=${nextIndex},media=disk,if=virtio,discard=on
             let nextIndex++
         fi
     else
-        echo "ERROR: unsupported disk_type \"$disk_type\""
+        echo "ERROR: unsupported disk type \"$diskN_type\""
         exit 2
     fi
     let disknum++
@@ -283,47 +283,47 @@ done
 
 IFS=$'\n'
 for cdname in $(set | awk -F= '$1 ~ /^cd[0-9]+_file$/ {print $0}' | grep -Eo "^cd[0-9]+" | sort -u); do
-    cd_file=$(set | awk -F= -v name="$cdname" '$1 == name "_file" {print $2}')
-    cd_type=$(set | awk -F= -v name="$cdname" '$1 == name "_type" {print $2}')
+    cdN_file=$(set | awk -F= -v name="$cdname" '$1 == name "_file" {print $2}')
+    cdN_type=$(set | awk -F= -v name="$cdname" '$1 == name "_type" {print $2}')
 
-    if [ -n "$cd_file" ]; then
-        if [ ! -e "$cd_file" -a -e "$cdPath"/"$cd_file" ]; then
-            cd1_file="$cdPath"/"$cd_file"
+    if [ -n "$cdN_file" ]; then
+        if [ ! -e "$cdN_file" -a -e "$cd_path"/"$cdN_file" ]; then
+            cdN_file="$cd_path"/"$cdN_file"
         fi
-        if [ ! -e "$cd_file" ]; then
+        if [ ! -e "$cdN_file" ]; then
             if [ "$dry_run" = 1 ]; then
-                echo "WARNING: cd_file \"$cd_file\" not found" >&2
+                echo "WARNING: cdN_file \"$cdN_file\" not found" >&2
             else
-                echo "ERROR: cd_file \"$cd_file\" not found" >&2
+                echo "ERROR: cdN_file \"$cdN_file\" not found" >&2
                 exit 2
             fi
         fi
     fi
-    if [ -z "$cd_type" ]; then
-        if [ -n "$cdType" ]; then
-            cd_type="$cdType"
+    if [ -z "$cdN_type" ]; then
+        if [ -n "$cd_type" ]; then
+            cdN_type="$cd_type"
         else
-            cd_type=ide
+            cdN_type=ide
         fi
     fi
 
-    if [ -n "$cd_file" ]; then
-        if [ "$cd_type" = "ide" ]; then
-            add -drive file=${cd_file},id=isocd"$nextIndex",media=cdrom,index="$nextIndex"
+    if [ -n "$cdN_file" ]; then
+        if [ "$cdN_type" = "ide" ]; then
+            add -drive file=${cdN_file},id=isocd"$nextIndex",media=cdrom,index="$nextIndex"
             let nextIndex++
-        elif [ "$cd_type" = "virtio" ]; then
-            if [ "$disk_type" = "virtio" ]; then
+        elif [ "$cdN_type" = "virtio" ]; then
+            if [ "$cdN_type" = "virtio" ]; then
                 add_virtio_bus
             fi
-            if [ -n "$cd_file" ]; then
-                add -drive file=${cd_file},id=isocd"$nextIndex",media=cdrom,index="$nextIndex"
+            if [ -n "$cdN_file" ]; then
+                add -drive file=${cdN_file},id=isocd"$nextIndex",media=cdrom,index="$nextIndex"
                 let nextIndex++
             fi
-        elif [ -z "$cd_type" -a -z "$cd_file" ]; then
+        elif [ -z "$cdN_type" -a -z "$cdN_file" ]; then
             # no cd
             echo -n
         else
-            echo "ERROR: unsupported cd_type \"$cd_type\""
+            echo "ERROR: unsupported cdN_type \"$cdN_type\""
             exit 2
         fi
     fi
